package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Alphabet;
import com.fois.Back_end_fois_smile.entity.AlphabetExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface AlphabetMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(AlphabetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(AlphabetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mabang);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Alphabet record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Alphabet record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Alphabet> selectByExample(AlphabetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Alphabet selectByPrimaryKey(String mabang);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Alphabet record, @Param("example") AlphabetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Alphabet record, @Param("example") AlphabetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Alphabet record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.alphabet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Alphabet record);

    @Select("select * from schema01.alphabet ORDER BY mabang")
    public ArrayList<Alphabet> getAll();
}