package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.ChildQuestion;
import com.fois.Back_end_fois_smile.entity.ChildQuestionExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface ChildQuestionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(ChildQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(ChildQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String machc);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(ChildQuestion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(ChildQuestion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<ChildQuestion> selectByExample(ChildQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    ChildQuestion selectByPrimaryKey(String machc);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") ChildQuestion record, @Param("example") ChildQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") ChildQuestion record, @Param("example") ChildQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(ChildQuestion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(ChildQuestion record);

    @Select("select * from schema01.child_question c where c.mach = #{mach} ORDER BY machc")
    public ArrayList<ChildQuestion> getAllChildQuestion(String mach);

}