package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Example;
import com.fois.Back_end_fois_smile.entity.ExampleExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface ExampleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mavd);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Example record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Example record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Example> selectByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Example selectByPrimaryKey(String mavd);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Example record, @Param("example") ExampleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Example record, @Param("example") ExampleExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Example record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.example
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Example record);

    @Select("select * from schema01.example e where e.matv = #{machu} ORDER BY mavd")
    public ArrayList<Example> getAllExample(String machu);
}