package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.KaiwaContent;
import com.fois.Back_end_fois_smile.entity.KaiwaContentExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface KaiwaContentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(KaiwaContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(KaiwaContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mand);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(KaiwaContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(KaiwaContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<KaiwaContent> selectByExample(KaiwaContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    KaiwaContent selectByPrimaryKey(String mand);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") KaiwaContent record, @Param("example") KaiwaContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") KaiwaContent record, @Param("example") KaiwaContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(KaiwaContent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kaiwa_content
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(KaiwaContent record);

    @Select("select * from schema01.kaiwa_content k where k.maht = #{maht} ORDER BY mand")
    public ArrayList<KaiwaContent> getAllKaiwaContent(String maht);
}