package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.KanjiSyllables;
import com.fois.Back_end_fois_smile.entity.KanjiSyllablesExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface KanjiSyllablesMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(KanjiSyllablesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(KanjiSyllablesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String maam);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(KanjiSyllables record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(KanjiSyllables record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<KanjiSyllables> selectByExample(KanjiSyllablesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    KanjiSyllables selectByPrimaryKey(String maam);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") KanjiSyllables record,
            @Param("example") KanjiSyllablesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") KanjiSyllables record, @Param("example") KanjiSyllablesExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(KanjiSyllables record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(KanjiSyllables record);

    @Select("select * from schema01.kanji_syllables s where s.machu = #{machu} and s.maloaiam = 'ON' ORDER BY maam")
    public ArrayList<KanjiSyllables> getAllOnyomi(String machu);
    
    @Select("select * from schema01.kanji_syllables s where s.machu = #{machu}  and s.maloaiam = 'KUN' ORDER BY maam")
    public ArrayList<KanjiSyllables> getAllKunnyomi(String machu);
}