package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.KanjiSyllablesType;
import com.fois.Back_end_fois_smile.entity.KanjiSyllablesTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KanjiSyllablesTypeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(KanjiSyllablesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(KanjiSyllablesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String maloaiam);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(KanjiSyllablesType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(KanjiSyllablesType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<KanjiSyllablesType> selectByExample(KanjiSyllablesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    KanjiSyllablesType selectByPrimaryKey(String maloaiam);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") KanjiSyllablesType record,
            @Param("example") KanjiSyllablesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") KanjiSyllablesType record,
            @Param("example") KanjiSyllablesTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(KanjiSyllablesType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kanji_syllables_type
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(KanjiSyllablesType record);
}