package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.KindOfQuestion;
import com.fois.Back_end_fois_smile.entity.KindOfQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KindOfQuestionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(KindOfQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(KindOfQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String maloaich);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(KindOfQuestion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(KindOfQuestion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<KindOfQuestion> selectByExample(KindOfQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    KindOfQuestion selectByPrimaryKey(String maloaich);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") KindOfQuestion record,
            @Param("example") KindOfQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") KindOfQuestion record, @Param("example") KindOfQuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(KindOfQuestion record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kind_of_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(KindOfQuestion record);
}