package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Lesson;
import com.fois.Back_end_fois_smile.entity.LessonExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface LessonMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mabh);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Lesson record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Lesson> selectByExample(LessonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Lesson selectByPrimaryKey(String mabh);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Lesson record, @Param("example") LessonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Lesson record, @Param("example") LessonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.lesson
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Lesson record);

    @Select("select * from schema01.lesson ORDER BY mabh")
    public ArrayList<Lesson> getAllLesson();
}