package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Progress;
import com.fois.Back_end_fois_smile.entity.ProgressExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface ProgressMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(ProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(ProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(Integer matd);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Progress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Progress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Progress> selectByExample(ProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Progress selectByPrimaryKey(Integer matd);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Progress record, @Param("example") ProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Progress record, @Param("example") ProgressExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Progress record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.progress
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Progress record);

    @Select("insert into schema01.progress (mabh, matk, tuvung) values (#{mabh}, #{matk}, #{tuvung})")
    public void insertProgress(String mabh, int matk, boolean tuvung);
    
    @Select("select * from schema01.progress WHERE mabh=#{mabh} and matk=#{matk}")
    public Progress selectByMabh(String mabh, int matk);
    
    @Select("select * from schema01.progress WHERE matk=#{matk} ORDER BY matd")
    public ArrayList<Progress> getAllProgress(int matk);
    
    @Select("select mabh from schema01.progress WHERE matk=#{matk} ORDER BY matd")
    public ArrayList<String> getMaBHProgress(int matk);
    
    @Select("UPDATE schema01.progress SET tuvung = true WHERE matk=#{matk} AND mabh=#{mabh};")
    public void updateVob(String mabh, int matk);
    
    @Select("UPDATE schema01.progress SET nguphap = true WHERE matk=#{matk} AND mabh=#{mabh};")
    public void updateNP(String mabh, int matk);
    
    @Select("UPDATE schema01.progress SET nghe = true WHERE matk=#{matk} AND mabh=#{mabh};")
    public void updateNghe(String mabh, int matk);
    
    @Select("UPDATE schema01.progress SET baitap = true WHERE matk=#{matk} AND mabh=#{mabh};")
    public void updateBT(String mabh, int matk);
}