package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Question;
import com.fois.Back_end_fois_smile.entity.QuestionExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface QuestionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mach);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Question selectByPrimaryKey(String mach);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Question record);

    @Select("select * from schema01.question q where q.mabai = #{mabai} ORDER BY mach")
    public ArrayList<Question> getAllQuestion(String mabai);
}