package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Reply;
import com.fois.Back_end_fois_smile.entity.ReplyExample;
import com.fois.Back_end_fois_smile.form.ReplyForm;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(Integer marep);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    List<Reply> selectByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    Reply selectByPrimaryKey(Integer marep);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schema01.reply
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Reply record);
    
    @Select("insert into schema01.reply (ndrep, thoigian, matk, mabl) values (#{ndrep}, #{thoigian}, #{matk}, #{mabl})")
    public void addReply(String ndrep, Date thoigian, int matk, int mabl);
    
    @Select("select a.hoten, r.ndrep, r.thoigian from schema01.reply r INNER JOIN schema01.account_information a ON r.matk=a.matk WHERE mabl=#{mabl} ORDER BY marep DESC")
    public ArrayList<ReplyForm> selectByMabl(int mabl);
}