package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Structure;
import com.fois.Back_end_fois_smile.entity.StructureExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface StructureMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(StructureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(StructureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mact);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Structure record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Structure record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Structure> selectByExample(StructureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Structure selectByPrimaryKey(String mact);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Structure record, @Param("example") StructureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Structure record, @Param("example") StructureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Structure record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.structure
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Structure record);

    @Select("select * from schema01.structure s where s.manp = #{manp} ORDER BY mact")
    public ArrayList<Structure> getAllStructure(String manp);
}