package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.TestTranscript;
import com.fois.Back_end_fois_smile.entity.TestTranscriptExample;
import com.fois.Back_end_fois_smile.form.TestTranscriptForm;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface TestTranscriptMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(TestTranscriptExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(TestTranscriptExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(Integer mabd);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(TestTranscript record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(TestTranscript record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<TestTranscript> selectByExample(TestTranscriptExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    TestTranscript selectByPrimaryKey(Integer mabd);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") TestTranscript record,
            @Param("example") TestTranscriptExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") TestTranscript record, @Param("example") TestTranscriptExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(TestTranscript record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test_transcript
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(TestTranscript record);

    @Select("insert into schema01.test_transcript (diem, matk, mabaikt, thoigian) values (#{diem}, #{matk}, #{mabaikt}, #{thoigian})")
    public void insertTestTranscript(TestTranscript record);
    
    @Select("SELECT a.diem, a.thoigian, t.tenbaikt FROM schema01.test_transcript a INNER JOIN schema01.test t ON t.mabaikt=a.mabaikt WHERE a.matk = #{matk} ORDER BY a.mabd")
    public ArrayList<TestTranscriptForm> getTestTranscript(int matk);
}