package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Test;
import com.fois.Back_end_fois_smile.entity.TestExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String mabaikt);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Test selectByPrimaryKey(String mabaikt);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Test record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.test
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Test record);

    @Select("select * from schema01.test ORDER BY mabaikt")
    public ArrayList<Test> getAllTest();
}