package com.fois.Back_end_fois_smile.mapper;

import com.fois.Back_end_fois_smile.entity.Vocabulary;
import com.fois.Back_end_fois_smile.entity.VocabularyExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface VocabularyMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(VocabularyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(VocabularyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String matv);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Vocabulary record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Vocabulary record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Vocabulary> selectByExample(VocabularyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Vocabulary selectByPrimaryKey(String matv);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Vocabulary record, @Param("example") VocabularyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Vocabulary record, @Param("example") VocabularyExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Vocabulary record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.vocabulary
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Vocabulary record);

    @Select("select * from schema01.vocabulary v where v.mabh = #{mabh} ORDER BY matv")
    public ArrayList<Vocabulary> getAllVocabulary(String mabh);
}