package com.fois.Back_end_fois_smile.mapper;
import com.fois.Back_end_fois_smile.entity.Word;
import com.fois.Back_end_fois_smile.entity.WordExample;
import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface WordMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    long countByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int deleteByPrimaryKey(String machu);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insert(Word record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int insertSelective(Word record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    List<Word> selectByExample(WordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    Word selectByPrimaryKey(String machu);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Word record, @Param("example") WordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByExample(@Param("record") Word record, @Param("example") WordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKeySelective(Word record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.word
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    int updateByPrimaryKey(Word record);

    @Select("select * from schema01.word w where w.mabang = 'LB001' and w.maloaitu = 'LTD' ORDER BY machu")
    public ArrayList<Word> getAllTDHiragana();
    
    @Select("select * from schema01.word w where w.mabang = 'LB001' and w.maloaitu = 'LTK' ORDER BY machu")
    public ArrayList<Word> getAllTKHiragana();
    
//    =======================================================
    @Select("select * from schema01.word w where w.mabang = 'LB002' and w.maloaitu = 'LTD' ORDER BY machu")
    public ArrayList<Word> getAllTDKatakana();
    
    @Select("select * from schema01.word w where w.mabang = 'LB002' and w.maloaitu = 'LTK' ORDER BY machu")
    public ArrayList<Word> getAllTKKatakana();
    
//  =======================================================
    @Select("select * from schema01.word w where w.mabang = 'LB003' and w.maloaitu = 'LTD' ORDER BY machu")
    public ArrayList<Word> getAllTDKanji();
    
    
}