package com.fois.Back_end_fois_smile.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AccountInformationExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public AccountInformationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMattIsNull() {
            addCriterion("matt is null");
            return (Criteria) this;
        }

        public Criteria andMattIsNotNull() {
            addCriterion("matt is not null");
            return (Criteria) this;
        }

        public Criteria andMattEqualTo(Integer value) {
            addCriterion("matt =", value, "matt");
            return (Criteria) this;
        }

        public Criteria andMattNotEqualTo(Integer value) {
            addCriterion("matt <>", value, "matt");
            return (Criteria) this;
        }

        public Criteria andMattGreaterThan(Integer value) {
            addCriterion("matt >", value, "matt");
            return (Criteria) this;
        }

        public Criteria andMattGreaterThanOrEqualTo(Integer value) {
            addCriterion("matt >=", value, "matt");
            return (Criteria) this;
        }

        public Criteria andMattLessThan(Integer value) {
            addCriterion("matt <", value, "matt");
            return (Criteria) this;
        }

        public Criteria andMattLessThanOrEqualTo(Integer value) {
            addCriterion("matt <=", value, "matt");
            return (Criteria) this;
        }

        public Criteria andMattIn(List<Integer> values) {
            addCriterion("matt in", values, "matt");
            return (Criteria) this;
        }

        public Criteria andMattNotIn(List<Integer> values) {
            addCriterion("matt not in", values, "matt");
            return (Criteria) this;
        }

        public Criteria andMattBetween(Integer value1, Integer value2) {
            addCriterion("matt between", value1, value2, "matt");
            return (Criteria) this;
        }

        public Criteria andMattNotBetween(Integer value1, Integer value2) {
            addCriterion("matt not between", value1, value2, "matt");
            return (Criteria) this;
        }

        public Criteria andHotenIsNull() {
            addCriterion("hoten is null");
            return (Criteria) this;
        }

        public Criteria andHotenIsNotNull() {
            addCriterion("hoten is not null");
            return (Criteria) this;
        }

        public Criteria andHotenEqualTo(String value) {
            addCriterion("hoten =", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotEqualTo(String value) {
            addCriterion("hoten <>", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenGreaterThan(String value) {
            addCriterion("hoten >", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenGreaterThanOrEqualTo(String value) {
            addCriterion("hoten >=", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLessThan(String value) {
            addCriterion("hoten <", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLessThanOrEqualTo(String value) {
            addCriterion("hoten <=", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLike(String value) {
            addCriterion("hoten like", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotLike(String value) {
            addCriterion("hoten not like", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenIn(List<String> values) {
            addCriterion("hoten in", values, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotIn(List<String> values) {
            addCriterion("hoten not in", values, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenBetween(String value1, String value2) {
            addCriterion("hoten between", value1, value2, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotBetween(String value1, String value2) {
            addCriterion("hoten not between", value1, value2, "hoten");
            return (Criteria) this;
        }

        public Criteria andNgaysinhIsNull() {
            addCriterion("ngaysinh is null");
            return (Criteria) this;
        }

        public Criteria andNgaysinhIsNotNull() {
            addCriterion("ngaysinh is not null");
            return (Criteria) this;
        }

        public Criteria andNgaysinhEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh =", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhNotEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh <>", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhGreaterThan(Date value) {
            addCriterionForJDBCDate("ngaysinh >", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh >=", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhLessThan(Date value) {
            addCriterionForJDBCDate("ngaysinh <", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ngaysinh <=", value, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhIn(List<Date> values) {
            addCriterionForJDBCDate("ngaysinh in", values, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhNotIn(List<Date> values) {
            addCriterionForJDBCDate("ngaysinh not in", values, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ngaysinh between", value1, value2, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andNgaysinhNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ngaysinh not between", value1, value2, "ngaysinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhIsNull() {
            addCriterion("gioitinh is null");
            return (Criteria) this;
        }

        public Criteria andGioitinhIsNotNull() {
            addCriterion("gioitinh is not null");
            return (Criteria) this;
        }

        public Criteria andGioitinhEqualTo(Integer value) {
            addCriterion("gioitinh =", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotEqualTo(Integer value) {
            addCriterion("gioitinh <>", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhGreaterThan(Integer value) {
            addCriterion("gioitinh >", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhGreaterThanOrEqualTo(Integer value) {
            addCriterion("gioitinh >=", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLessThan(Integer value) {
            addCriterion("gioitinh <", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhLessThanOrEqualTo(Integer value) {
            addCriterion("gioitinh <=", value, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhIn(List<Integer> values) {
            addCriterion("gioitinh in", values, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotIn(List<Integer> values) {
            addCriterion("gioitinh not in", values, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhBetween(Integer value1, Integer value2) {
            addCriterion("gioitinh between", value1, value2, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andGioitinhNotBetween(Integer value1, Integer value2) {
            addCriterion("gioitinh not between", value1, value2, "gioitinh");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNull() {
            addCriterion("diachi is null");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNotNull() {
            addCriterion("diachi is not null");
            return (Criteria) this;
        }

        public Criteria andDiachiEqualTo(String value) {
            addCriterion("diachi =", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotEqualTo(String value) {
            addCriterion("diachi <>", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThan(String value) {
            addCriterion("diachi >", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThanOrEqualTo(String value) {
            addCriterion("diachi >=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThan(String value) {
            addCriterion("diachi <", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThanOrEqualTo(String value) {
            addCriterion("diachi <=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLike(String value) {
            addCriterion("diachi like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotLike(String value) {
            addCriterion("diachi not like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiIn(List<String> values) {
            addCriterion("diachi in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotIn(List<String> values) {
            addCriterion("diachi not in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiBetween(String value1, String value2) {
            addCriterion("diachi between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotBetween(String value1, String value2) {
            addCriterion("diachi not between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andMatkIsNull() {
            addCriterion("matk is null");
            return (Criteria) this;
        }

        public Criteria andMatkIsNotNull() {
            addCriterion("matk is not null");
            return (Criteria) this;
        }

        public Criteria andMatkEqualTo(Integer value) {
            addCriterion("matk =", value, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkNotEqualTo(Integer value) {
            addCriterion("matk <>", value, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkGreaterThan(Integer value) {
            addCriterion("matk >", value, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkGreaterThanOrEqualTo(Integer value) {
            addCriterion("matk >=", value, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkLessThan(Integer value) {
            addCriterion("matk <", value, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkLessThanOrEqualTo(Integer value) {
            addCriterion("matk <=", value, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkIn(List<Integer> values) {
            addCriterion("matk in", values, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkNotIn(List<Integer> values) {
            addCriterion("matk not in", values, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkBetween(Integer value1, Integer value2) {
            addCriterion("matk between", value1, value2, "matk");
            return (Criteria) this;
        }

        public Criteria andMatkNotBetween(Integer value1, Integer value2) {
            addCriterion("matk not between", value1, value2, "matk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.account_information
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schema01. account_information
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 27 20:05:54 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}