package com.fois.Back_end_fois_smile.entity;

import java.util.Date;

public class Account {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.account.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Integer matk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.account.username
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.account.password
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.account.loaitk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Integer loaitk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.account.thoigiandn
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Date thoigiandn;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.account.matk
     * @return  the value of schema01.account.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMatk() {
        return matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.account.matk
     * @param matk  the value for schema01.account.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMatk(Integer matk) {
        this.matk = matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.account.username
     * @return  the value of schema01.account.username
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.account.username
     * @param username  the value for schema01.account.username
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.account.password
     * @return  the value of schema01.account.password
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.account.password
     * @param password  the value for schema01.account.password
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.account.loaitk
     * @return  the value of schema01.account.loaitk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Integer getLoaitk() {
        return loaitk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.account.loaitk
     * @param loaitk  the value for schema01.account.loaitk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setLoaitk(Integer loaitk) {
        this.loaitk = loaitk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.account.thoigiandn
     * @return  the value of schema01.account.thoigiandn
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Date getThoigiandn() {
        return thoigiandn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.account.thoigiandn
     * @param thoigiandn  the value for schema01.account.thoigiandn
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setThoigiandn(Date thoigiandn) {
        this.thoigiandn = thoigiandn;
    }
}