package com.fois.Back_end_fois_smile.entity;

public class Answer {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.answer.mada
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mada;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.answer.tenda
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenda;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.answer.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String machc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.answer.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String hinhanh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.answer.mada
     * @return  the value of schema01.answer.mada
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMada() {
        return mada;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.answer.mada
     * @param mada  the value for schema01.answer.mada
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMada(String mada) {
        this.mada = mada;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.answer.tenda
     * @return  the value of schema01.answer.tenda
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenda() {
        return tenda;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.answer.tenda
     * @param tenda  the value for schema01.answer.tenda
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenda(String tenda) {
        this.tenda = tenda;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.answer.machc
     * @return  the value of schema01.answer.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMachc() {
        return machc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.answer.machc
     * @param machc  the value for schema01.answer.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMachc(String machc) {
        this.machc = machc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.answer.hinhanh
     * @return  the value of schema01.answer.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getHinhanh() {
        return hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.answer.hinhanh
     * @param hinhanh  the value for schema01.answer.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
}