package com.fois.Back_end_fois_smile.entity;

import java.util.ArrayList;
import java.util.List;

public class ChildQuestionExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public ChildQuestionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMachcIsNull() {
            addCriterion("machc is null");
            return (Criteria) this;
        }

        public Criteria andMachcIsNotNull() {
            addCriterion("machc is not null");
            return (Criteria) this;
        }

        public Criteria andMachcEqualTo(String value) {
            addCriterion("machc =", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotEqualTo(String value) {
            addCriterion("machc <>", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcGreaterThan(String value) {
            addCriterion("machc >", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcGreaterThanOrEqualTo(String value) {
            addCriterion("machc >=", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcLessThan(String value) {
            addCriterion("machc <", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcLessThanOrEqualTo(String value) {
            addCriterion("machc <=", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcLike(String value) {
            addCriterion("machc like", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotLike(String value) {
            addCriterion("machc not like", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcIn(List<String> values) {
            addCriterion("machc in", values, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotIn(List<String> values) {
            addCriterion("machc not in", values, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcBetween(String value1, String value2) {
            addCriterion("machc between", value1, value2, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotBetween(String value1, String value2) {
            addCriterion("machc not between", value1, value2, "machc");
            return (Criteria) this;
        }

        public Criteria andTenchcIsNull() {
            addCriterion("tenchc is null");
            return (Criteria) this;
        }

        public Criteria andTenchcIsNotNull() {
            addCriterion("tenchc is not null");
            return (Criteria) this;
        }

        public Criteria andTenchcEqualTo(String value) {
            addCriterion("tenchc =", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcNotEqualTo(String value) {
            addCriterion("tenchc <>", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcGreaterThan(String value) {
            addCriterion("tenchc >", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcGreaterThanOrEqualTo(String value) {
            addCriterion("tenchc >=", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcLessThan(String value) {
            addCriterion("tenchc <", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcLessThanOrEqualTo(String value) {
            addCriterion("tenchc <=", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcLike(String value) {
            addCriterion("tenchc like", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcNotLike(String value) {
            addCriterion("tenchc not like", value, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcIn(List<String> values) {
            addCriterion("tenchc in", values, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcNotIn(List<String> values) {
            addCriterion("tenchc not in", values, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcBetween(String value1, String value2) {
            addCriterion("tenchc between", value1, value2, "tenchc");
            return (Criteria) this;
        }

        public Criteria andTenchcNotBetween(String value1, String value2) {
            addCriterion("tenchc not between", value1, value2, "tenchc");
            return (Criteria) this;
        }

        public Criteria andDiemIsNull() {
            addCriterion("diem is null");
            return (Criteria) this;
        }

        public Criteria andDiemIsNotNull() {
            addCriterion("diem is not null");
            return (Criteria) this;
        }

        public Criteria andDiemEqualTo(Float value) {
            addCriterion("diem =", value, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemNotEqualTo(Float value) {
            addCriterion("diem <>", value, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemGreaterThan(Float value) {
            addCriterion("diem >", value, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemGreaterThanOrEqualTo(Float value) {
            addCriterion("diem >=", value, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemLessThan(Float value) {
            addCriterion("diem <", value, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemLessThanOrEqualTo(Float value) {
            addCriterion("diem <=", value, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemIn(List<Float> values) {
            addCriterion("diem in", values, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemNotIn(List<Float> values) {
            addCriterion("diem not in", values, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemBetween(Float value1, Float value2) {
            addCriterion("diem between", value1, value2, "diem");
            return (Criteria) this;
        }

        public Criteria andDiemNotBetween(Float value1, Float value2) {
            addCriterion("diem not between", value1, value2, "diem");
            return (Criteria) this;
        }

        public Criteria andLinkaudioIsNull() {
            addCriterion("linkaudio is null");
            return (Criteria) this;
        }

        public Criteria andLinkaudioIsNotNull() {
            addCriterion("linkaudio is not null");
            return (Criteria) this;
        }

        public Criteria andLinkaudioEqualTo(String value) {
            addCriterion("linkaudio =", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioNotEqualTo(String value) {
            addCriterion("linkaudio <>", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioGreaterThan(String value) {
            addCriterion("linkaudio >", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioGreaterThanOrEqualTo(String value) {
            addCriterion("linkaudio >=", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioLessThan(String value) {
            addCriterion("linkaudio <", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioLessThanOrEqualTo(String value) {
            addCriterion("linkaudio <=", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioLike(String value) {
            addCriterion("linkaudio like", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioNotLike(String value) {
            addCriterion("linkaudio not like", value, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioIn(List<String> values) {
            addCriterion("linkaudio in", values, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioNotIn(List<String> values) {
            addCriterion("linkaudio not in", values, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioBetween(String value1, String value2) {
            addCriterion("linkaudio between", value1, value2, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andLinkaudioNotBetween(String value1, String value2) {
            addCriterion("linkaudio not between", value1, value2, "linkaudio");
            return (Criteria) this;
        }

        public Criteria andMachIsNull() {
            addCriterion("mach is null");
            return (Criteria) this;
        }

        public Criteria andMachIsNotNull() {
            addCriterion("mach is not null");
            return (Criteria) this;
        }

        public Criteria andMachEqualTo(String value) {
            addCriterion("mach =", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachNotEqualTo(String value) {
            addCriterion("mach <>", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachGreaterThan(String value) {
            addCriterion("mach >", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachGreaterThanOrEqualTo(String value) {
            addCriterion("mach >=", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachLessThan(String value) {
            addCriterion("mach <", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachLessThanOrEqualTo(String value) {
            addCriterion("mach <=", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachLike(String value) {
            addCriterion("mach like", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachNotLike(String value) {
            addCriterion("mach not like", value, "mach");
            return (Criteria) this;
        }

        public Criteria andMachIn(List<String> values) {
            addCriterion("mach in", values, "mach");
            return (Criteria) this;
        }

        public Criteria andMachNotIn(List<String> values) {
            addCriterion("mach not in", values, "mach");
            return (Criteria) this;
        }

        public Criteria andMachBetween(String value1, String value2) {
            addCriterion("mach between", value1, value2, "mach");
            return (Criteria) this;
        }

        public Criteria andMachNotBetween(String value1, String value2) {
            addCriterion("mach not between", value1, value2, "mach");
            return (Criteria) this;
        }

        public Criteria andMaloaichIsNull() {
            addCriterion("maloaich is null");
            return (Criteria) this;
        }

        public Criteria andMaloaichIsNotNull() {
            addCriterion("maloaich is not null");
            return (Criteria) this;
        }

        public Criteria andMaloaichEqualTo(String value) {
            addCriterion("maloaich =", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichNotEqualTo(String value) {
            addCriterion("maloaich <>", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichGreaterThan(String value) {
            addCriterion("maloaich >", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichGreaterThanOrEqualTo(String value) {
            addCriterion("maloaich >=", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichLessThan(String value) {
            addCriterion("maloaich <", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichLessThanOrEqualTo(String value) {
            addCriterion("maloaich <=", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichLike(String value) {
            addCriterion("maloaich like", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichNotLike(String value) {
            addCriterion("maloaich not like", value, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichIn(List<String> values) {
            addCriterion("maloaich in", values, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichNotIn(List<String> values) {
            addCriterion("maloaich not in", values, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichBetween(String value1, String value2) {
            addCriterion("maloaich between", value1, value2, "maloaich");
            return (Criteria) this;
        }

        public Criteria andMaloaichNotBetween(String value1, String value2) {
            addCriterion("maloaich not between", value1, value2, "maloaich");
            return (Criteria) this;
        }

        public Criteria andHinhanhIsNull() {
            addCriterion("hinhanh is null");
            return (Criteria) this;
        }

        public Criteria andHinhanhIsNotNull() {
            addCriterion("hinhanh is not null");
            return (Criteria) this;
        }

        public Criteria andHinhanhEqualTo(String value) {
            addCriterion("hinhanh =", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhNotEqualTo(String value) {
            addCriterion("hinhanh <>", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhGreaterThan(String value) {
            addCriterion("hinhanh >", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhGreaterThanOrEqualTo(String value) {
            addCriterion("hinhanh >=", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhLessThan(String value) {
            addCriterion("hinhanh <", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhLessThanOrEqualTo(String value) {
            addCriterion("hinhanh <=", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhLike(String value) {
            addCriterion("hinhanh like", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhNotLike(String value) {
            addCriterion("hinhanh not like", value, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhIn(List<String> values) {
            addCriterion("hinhanh in", values, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhNotIn(List<String> values) {
            addCriterion("hinhanh not in", values, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhBetween(String value1, String value2) {
            addCriterion("hinhanh between", value1, value2, "hinhanh");
            return (Criteria) this;
        }

        public Criteria andHinhanhNotBetween(String value1, String value2) {
            addCriterion("hinhanh not between", value1, value2, "hinhanh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.child_question
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schema01.child_question
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 12 14:23:57 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}