package com.fois.Back_end_fois_smile.entity;

public class ChildQuestion {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String machc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.tenchc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenchc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.diem
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Float diem;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.linkaudio
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String linkaudio;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.mach
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mach;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.maloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maloaich;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.child_question.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String hinhanh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.machc
     * @return  the value of schema01.child_question.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMachc() {
        return machc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.machc
     * @param machc  the value for schema01.child_question.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMachc(String machc) {
        this.machc = machc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.tenchc
     * @return  the value of schema01.child_question.tenchc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenchc() {
        return tenchc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.tenchc
     * @param tenchc  the value for schema01.child_question.tenchc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenchc(String tenchc) {
        this.tenchc = tenchc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.diem
     * @return  the value of schema01.child_question.diem
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Float getDiem() {
        return diem;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.diem
     * @param diem  the value for schema01.child_question.diem
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDiem(Float diem) {
        this.diem = diem;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.linkaudio
     * @return  the value of schema01.child_question.linkaudio
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getLinkaudio() {
        return linkaudio;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.linkaudio
     * @param linkaudio  the value for schema01.child_question.linkaudio
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setLinkaudio(String linkaudio) {
        this.linkaudio = linkaudio;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.mach
     * @return  the value of schema01.child_question.mach
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMach() {
        return mach;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.mach
     * @param mach  the value for schema01.child_question.mach
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMach(String mach) {
        this.mach = mach;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.maloaich
     * @return  the value of schema01.child_question.maloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaloaich() {
        return maloaich;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.maloaich
     * @param maloaich  the value for schema01.child_question.maloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaloaich(String maloaich) {
        this.maloaich = maloaich;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.child_question.hinhanh
     * @return  the value of schema01.child_question.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getHinhanh() {
        return hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.child_question.hinhanh
     * @param hinhanh  the value for schema01.child_question.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
}