package com.fois.Back_end_fois_smile.entity;

import java.util.Date;

public class Comment {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.comment.mabl
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Integer mabl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.comment.ndbl
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String ndbl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.comment.thoigian
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Date thoigian;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.comment.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Integer matk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.comment.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.comment.mabl
     * @return  the value of schema01.comment.mabl
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMabl() {
        return mabl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.comment.mabl
     * @param mabl  the value for schema01.comment.mabl
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabl(Integer mabl) {
        this.mabl = mabl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.comment.ndbl
     * @return  the value of schema01.comment.ndbl
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getNdbl() {
        return ndbl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.comment.ndbl
     * @param ndbl  the value for schema01.comment.ndbl
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNdbl(String ndbl) {
        this.ndbl = ndbl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.comment.thoigian
     * @return  the value of schema01.comment.thoigian
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Date getThoigian() {
        return thoigian;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.comment.thoigian
     * @param thoigian  the value for schema01.comment.thoigian
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setThoigian(Date thoigian) {
        this.thoigian = thoigian;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.comment.matk
     * @return  the value of schema01.comment.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMatk() {
        return matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.comment.matk
     * @param matk  the value for schema01.comment.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMatk(Integer matk) {
        this.matk = matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.comment.mabh
     * @return  the value of schema01.comment.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabh() {
        return mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.comment.mabh
     * @param mabh  the value for schema01.comment.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabh(String mabh) {
        this.mabh = mabh;
    }
}