package com.fois.Back_end_fois_smile.entity;

import java.util.ArrayList;
import java.util.List;

public class CorrectAnswerExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public CorrectAnswerExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMadadungIsNull() {
            addCriterion("madadung is null");
            return (Criteria) this;
        }

        public Criteria andMadadungIsNotNull() {
            addCriterion("madadung is not null");
            return (Criteria) this;
        }

        public Criteria andMadadungEqualTo(String value) {
            addCriterion("madadung =", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungNotEqualTo(String value) {
            addCriterion("madadung <>", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungGreaterThan(String value) {
            addCriterion("madadung >", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungGreaterThanOrEqualTo(String value) {
            addCriterion("madadung >=", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungLessThan(String value) {
            addCriterion("madadung <", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungLessThanOrEqualTo(String value) {
            addCriterion("madadung <=", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungLike(String value) {
            addCriterion("madadung like", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungNotLike(String value) {
            addCriterion("madadung not like", value, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungIn(List<String> values) {
            addCriterion("madadung in", values, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungNotIn(List<String> values) {
            addCriterion("madadung not in", values, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungBetween(String value1, String value2) {
            addCriterion("madadung between", value1, value2, "madadung");
            return (Criteria) this;
        }

        public Criteria andMadadungNotBetween(String value1, String value2) {
            addCriterion("madadung not between", value1, value2, "madadung");
            return (Criteria) this;
        }

        public Criteria andTendadungIsNull() {
            addCriterion("tendadung is null");
            return (Criteria) this;
        }

        public Criteria andTendadungIsNotNull() {
            addCriterion("tendadung is not null");
            return (Criteria) this;
        }

        public Criteria andTendadungEqualTo(String value) {
            addCriterion("tendadung =", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungNotEqualTo(String value) {
            addCriterion("tendadung <>", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungGreaterThan(String value) {
            addCriterion("tendadung >", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungGreaterThanOrEqualTo(String value) {
            addCriterion("tendadung >=", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungLessThan(String value) {
            addCriterion("tendadung <", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungLessThanOrEqualTo(String value) {
            addCriterion("tendadung <=", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungLike(String value) {
            addCriterion("tendadung like", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungNotLike(String value) {
            addCriterion("tendadung not like", value, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungIn(List<String> values) {
            addCriterion("tendadung in", values, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungNotIn(List<String> values) {
            addCriterion("tendadung not in", values, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungBetween(String value1, String value2) {
            addCriterion("tendadung between", value1, value2, "tendadung");
            return (Criteria) this;
        }

        public Criteria andTendadungNotBetween(String value1, String value2) {
            addCriterion("tendadung not between", value1, value2, "tendadung");
            return (Criteria) this;
        }

        public Criteria andMachcIsNull() {
            addCriterion("machc is null");
            return (Criteria) this;
        }

        public Criteria andMachcIsNotNull() {
            addCriterion("machc is not null");
            return (Criteria) this;
        }

        public Criteria andMachcEqualTo(String value) {
            addCriterion("machc =", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotEqualTo(String value) {
            addCriterion("machc <>", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcGreaterThan(String value) {
            addCriterion("machc >", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcGreaterThanOrEqualTo(String value) {
            addCriterion("machc >=", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcLessThan(String value) {
            addCriterion("machc <", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcLessThanOrEqualTo(String value) {
            addCriterion("machc <=", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcLike(String value) {
            addCriterion("machc like", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotLike(String value) {
            addCriterion("machc not like", value, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcIn(List<String> values) {
            addCriterion("machc in", values, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotIn(List<String> values) {
            addCriterion("machc not in", values, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcBetween(String value1, String value2) {
            addCriterion("machc between", value1, value2, "machc");
            return (Criteria) this;
        }

        public Criteria andMachcNotBetween(String value1, String value2) {
            addCriterion("machc not between", value1, value2, "machc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.correct_answer
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schema01.correct_answer
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 19 10:22:03 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}