package com.fois.Back_end_fois_smile.entity;

public class CorrectAnswer {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.correct_answer.madadung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String madadung;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.correct_answer.tendadung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tendadung;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.correct_answer.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String machc;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.correct_answer.madadung
     * @return  the value of schema01.correct_answer.madadung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMadadung() {
        return madadung;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.correct_answer.madadung
     * @param madadung  the value for schema01.correct_answer.madadung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMadadung(String madadung) {
        this.madadung = madadung;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.correct_answer.tendadung
     * @return  the value of schema01.correct_answer.tendadung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTendadung() {
        return tendadung;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.correct_answer.tendadung
     * @param tendadung  the value for schema01.correct_answer.tendadung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTendadung(String tendadung) {
        this.tendadung = tendadung;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.correct_answer.machc
     * @return  the value of schema01.correct_answer.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMachc() {
        return machc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.correct_answer.machc
     * @param machc  the value for schema01.correct_answer.machc
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMachc(String machc) {
        this.machc = machc;
    }
}