package com.fois.Back_end_fois_smile.entity;

public class Grammar {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.grammar.manp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String manp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.grammar.tennp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tennp;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.grammar.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.grammar.manp
     * @return  the value of schema01.grammar.manp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getManp() {
        return manp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.grammar.manp
     * @param manp  the value for schema01.grammar.manp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setManp(String manp) {
        this.manp = manp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.grammar.tennp
     * @return  the value of schema01.grammar.tennp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTennp() {
        return tennp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.grammar.tennp
     * @param tennp  the value for schema01.grammar.tennp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTennp(String tennp) {
        this.tennp = tennp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.grammar.mabh
     * @return  the value of schema01.grammar.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabh() {
        return mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.grammar.mabh
     * @param mabh  the value for schema01.grammar.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabh(String mabh) {
        this.mabh = mabh;
    }
}