package com.fois.Back_end_fois_smile.entity;

import java.util.ArrayList;
import java.util.List;

public class GrammarExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public GrammarExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andManpIsNull() {
            addCriterion("manp is null");
            return (Criteria) this;
        }

        public Criteria andManpIsNotNull() {
            addCriterion("manp is not null");
            return (Criteria) this;
        }

        public Criteria andManpEqualTo(String value) {
            addCriterion("manp =", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpNotEqualTo(String value) {
            addCriterion("manp <>", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpGreaterThan(String value) {
            addCriterion("manp >", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpGreaterThanOrEqualTo(String value) {
            addCriterion("manp >=", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpLessThan(String value) {
            addCriterion("manp <", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpLessThanOrEqualTo(String value) {
            addCriterion("manp <=", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpLike(String value) {
            addCriterion("manp like", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpNotLike(String value) {
            addCriterion("manp not like", value, "manp");
            return (Criteria) this;
        }

        public Criteria andManpIn(List<String> values) {
            addCriterion("manp in", values, "manp");
            return (Criteria) this;
        }

        public Criteria andManpNotIn(List<String> values) {
            addCriterion("manp not in", values, "manp");
            return (Criteria) this;
        }

        public Criteria andManpBetween(String value1, String value2) {
            addCriterion("manp between", value1, value2, "manp");
            return (Criteria) this;
        }

        public Criteria andManpNotBetween(String value1, String value2) {
            addCriterion("manp not between", value1, value2, "manp");
            return (Criteria) this;
        }

        public Criteria andTennpIsNull() {
            addCriterion("tennp is null");
            return (Criteria) this;
        }

        public Criteria andTennpIsNotNull() {
            addCriterion("tennp is not null");
            return (Criteria) this;
        }

        public Criteria andTennpEqualTo(String value) {
            addCriterion("tennp =", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpNotEqualTo(String value) {
            addCriterion("tennp <>", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpGreaterThan(String value) {
            addCriterion("tennp >", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpGreaterThanOrEqualTo(String value) {
            addCriterion("tennp >=", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpLessThan(String value) {
            addCriterion("tennp <", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpLessThanOrEqualTo(String value) {
            addCriterion("tennp <=", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpLike(String value) {
            addCriterion("tennp like", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpNotLike(String value) {
            addCriterion("tennp not like", value, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpIn(List<String> values) {
            addCriterion("tennp in", values, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpNotIn(List<String> values) {
            addCriterion("tennp not in", values, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpBetween(String value1, String value2) {
            addCriterion("tennp between", value1, value2, "tennp");
            return (Criteria) this;
        }

        public Criteria andTennpNotBetween(String value1, String value2) {
            addCriterion("tennp not between", value1, value2, "tennp");
            return (Criteria) this;
        }

        public Criteria andMabhIsNull() {
            addCriterion("mabh is null");
            return (Criteria) this;
        }

        public Criteria andMabhIsNotNull() {
            addCriterion("mabh is not null");
            return (Criteria) this;
        }

        public Criteria andMabhEqualTo(String value) {
            addCriterion("mabh =", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotEqualTo(String value) {
            addCriterion("mabh <>", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhGreaterThan(String value) {
            addCriterion("mabh >", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhGreaterThanOrEqualTo(String value) {
            addCriterion("mabh >=", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhLessThan(String value) {
            addCriterion("mabh <", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhLessThanOrEqualTo(String value) {
            addCriterion("mabh <=", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhLike(String value) {
            addCriterion("mabh like", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotLike(String value) {
            addCriterion("mabh not like", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhIn(List<String> values) {
            addCriterion("mabh in", values, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotIn(List<String> values) {
            addCriterion("mabh not in", values, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhBetween(String value1, String value2) {
            addCriterion("mabh between", value1, value2, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotBetween(String value1, String value2) {
            addCriterion("mabh not between", value1, value2, "mabh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.grammar
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schema01.grammar
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 09 11:56:10 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}