package com.fois.Back_end_fois_smile.entity;

public class KaiwaContent {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa_content.mand
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mand;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa_content.noidung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String noidung;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa_content.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String nghia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa_content.linkaudio
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String linkaudio;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa_content.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String hinhanh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kaiwa_content.maht
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maht;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa_content.mand
     * @return  the value of schema01.kaiwa_content.mand
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMand() {
        return mand;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa_content.mand
     * @param mand  the value for schema01.kaiwa_content.mand
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMand(String mand) {
        this.mand = mand;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa_content.noidung
     * @return  the value of schema01.kaiwa_content.noidung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getNoidung() {
        return noidung;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa_content.noidung
     * @param noidung  the value for schema01.kaiwa_content.noidung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa_content.nghia
     * @return  the value of schema01.kaiwa_content.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getNghia() {
        return nghia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa_content.nghia
     * @param nghia  the value for schema01.kaiwa_content.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNghia(String nghia) {
        this.nghia = nghia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa_content.linkaudio
     * @return  the value of schema01.kaiwa_content.linkaudio
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getLinkaudio() {
        return linkaudio;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa_content.linkaudio
     * @param linkaudio  the value for schema01.kaiwa_content.linkaudio
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setLinkaudio(String linkaudio) {
        this.linkaudio = linkaudio;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa_content.hinhanh
     * @return  the value of schema01.kaiwa_content.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getHinhanh() {
        return hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa_content.hinhanh
     * @param hinhanh  the value for schema01.kaiwa_content.hinhanh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kaiwa_content.maht
     * @return  the value of schema01.kaiwa_content.maht
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaht() {
        return maht;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kaiwa_content.maht
     * @param maht  the value for schema01.kaiwa_content.maht
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaht(String maht) {
        this.maht = maht;
    }
}