package com.fois.Back_end_fois_smile.entity;

public class KanjiSyllablesType {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kanji_syllables_type.maloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maloaiam;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kanji_syllables_type.tenloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenloaiam;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kanji_syllables_type.maloaiam
     * @return  the value of schema01.kanji_syllables_type.maloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaloaiam() {
        return maloaiam;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kanji_syllables_type.maloaiam
     * @param maloaiam  the value for schema01.kanji_syllables_type.maloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaloaiam(String maloaiam) {
        this.maloaiam = maloaiam;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kanji_syllables_type.tenloaiam
     * @return  the value of schema01.kanji_syllables_type.tenloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenloaiam() {
        return tenloaiam;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kanji_syllables_type.tenloaiam
     * @param tenloaiam  the value for schema01.kanji_syllables_type.tenloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenloaiam(String tenloaiam) {
        this.tenloaiam = tenloaiam;
    }
}