package com.fois.Back_end_fois_smile.entity;

public class KanjiSyllables {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kanji_syllables.maam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maam;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kanji_syllables.tenam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenam;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kanji_syllables.machu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String machu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kanji_syllables.maloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maloaiam;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kanji_syllables.maam
     * @return  the value of schema01.kanji_syllables.maam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaam() {
        return maam;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kanji_syllables.maam
     * @param maam  the value for schema01.kanji_syllables.maam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaam(String maam) {
        this.maam = maam;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kanji_syllables.tenam
     * @return  the value of schema01.kanji_syllables.tenam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenam() {
        return tenam;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kanji_syllables.tenam
     * @param tenam  the value for schema01.kanji_syllables.tenam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenam(String tenam) {
        this.tenam = tenam;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kanji_syllables.machu
     * @return  the value of schema01.kanji_syllables.machu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMachu() {
        return machu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kanji_syllables.machu
     * @param machu  the value for schema01.kanji_syllables.machu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMachu(String machu) {
        this.machu = machu;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kanji_syllables.maloaiam
     * @return  the value of schema01.kanji_syllables.maloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaloaiam() {
        return maloaiam;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kanji_syllables.maloaiam
     * @param maloaiam  the value for schema01.kanji_syllables.maloaiam
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaloaiam(String maloaiam) {
        this.maloaiam = maloaiam;
    }
}