package com.fois.Back_end_fois_smile.entity;

public class Kindofword {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kindofword.maloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maloaitu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kindofword.tenloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenloaitu;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kindofword.maloaitu
     * @return  the value of schema01.kindofword.maloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaloaitu() {
        return maloaitu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kindofword.maloaitu
     * @param maloaitu  the value for schema01.kindofword.maloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaloaitu(String maloaitu) {
        this.maloaitu = maloaitu;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kindofword.tenloaitu
     * @return  the value of schema01.kindofword.tenloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenloaitu() {
        return tenloaitu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kindofword.tenloaitu
     * @param tenloaitu  the value for schema01.kindofword.tenloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenloaitu(String tenloaitu) {
        this.tenloaitu = tenloaitu;
    }
}