package com.fois.Back_end_fois_smile.entity;

public class KindOfQuestion {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kind_of_question.maloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maloaich;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.kind_of_question.tenloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenloaich;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kind_of_question.maloaich
     * @return  the value of schema01.kind_of_question.maloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaloaich() {
        return maloaich;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kind_of_question.maloaich
     * @param maloaich  the value for schema01.kind_of_question.maloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaloaich(String maloaich) {
        this.maloaich = maloaich;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.kind_of_question.tenloaich
     * @return  the value of schema01.kind_of_question.tenloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenloaich() {
        return tenloaich;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.kind_of_question.tenloaich
     * @param tenloaich  the value for schema01.kind_of_question.tenloaich
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenloaich(String tenloaich) {
        this.tenloaich = tenloaich;
    }
}