package com.fois.Back_end_fois_smile.entity;

import java.util.ArrayList;
import java.util.List;

public class KindofwordExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public KindofwordExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaloaituIsNull() {
            addCriterion("maloaitu is null");
            return (Criteria) this;
        }

        public Criteria andMaloaituIsNotNull() {
            addCriterion("maloaitu is not null");
            return (Criteria) this;
        }

        public Criteria andMaloaituEqualTo(String value) {
            addCriterion("maloaitu =", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituNotEqualTo(String value) {
            addCriterion("maloaitu <>", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituGreaterThan(String value) {
            addCriterion("maloaitu >", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituGreaterThanOrEqualTo(String value) {
            addCriterion("maloaitu >=", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituLessThan(String value) {
            addCriterion("maloaitu <", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituLessThanOrEqualTo(String value) {
            addCriterion("maloaitu <=", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituLike(String value) {
            addCriterion("maloaitu like", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituNotLike(String value) {
            addCriterion("maloaitu not like", value, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituIn(List<String> values) {
            addCriterion("maloaitu in", values, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituNotIn(List<String> values) {
            addCriterion("maloaitu not in", values, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituBetween(String value1, String value2) {
            addCriterion("maloaitu between", value1, value2, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andMaloaituNotBetween(String value1, String value2) {
            addCriterion("maloaitu not between", value1, value2, "maloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituIsNull() {
            addCriterion("tenloaitu is null");
            return (Criteria) this;
        }

        public Criteria andTenloaituIsNotNull() {
            addCriterion("tenloaitu is not null");
            return (Criteria) this;
        }

        public Criteria andTenloaituEqualTo(String value) {
            addCriterion("tenloaitu =", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituNotEqualTo(String value) {
            addCriterion("tenloaitu <>", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituGreaterThan(String value) {
            addCriterion("tenloaitu >", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituGreaterThanOrEqualTo(String value) {
            addCriterion("tenloaitu >=", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituLessThan(String value) {
            addCriterion("tenloaitu <", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituLessThanOrEqualTo(String value) {
            addCriterion("tenloaitu <=", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituLike(String value) {
            addCriterion("tenloaitu like", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituNotLike(String value) {
            addCriterion("tenloaitu not like", value, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituIn(List<String> values) {
            addCriterion("tenloaitu in", values, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituNotIn(List<String> values) {
            addCriterion("tenloaitu not in", values, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituBetween(String value1, String value2) {
            addCriterion("tenloaitu between", value1, value2, "tenloaitu");
            return (Criteria) this;
        }

        public Criteria andTenloaituNotBetween(String value1, String value2) {
            addCriterion("tenloaitu not between", value1, value2, "tenloaitu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.kindofword
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schema01.kindofword
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 31 06:58:33 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}