package com.fois.Back_end_fois_smile.entity;

public class Lesson {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.lesson.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.lesson.tenbh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenbh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.lesson.mabh
     * @return  the value of schema01.lesson.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabh() {
        return mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.lesson.mabh
     * @param mabh  the value for schema01.lesson.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabh(String mabh) {
        this.mabh = mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.lesson.tenbh
     * @return  the value of schema01.lesson.tenbh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenbh() {
        return tenbh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.lesson.tenbh
     * @param tenbh  the value for schema01.lesson.tenbh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenbh(String tenbh) {
        this.tenbh = tenbh;
    }
}