package com.fois.Back_end_fois_smile.entity;

import java.util.ArrayList;
import java.util.List;

public class ListeningExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public ListeningExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMabaingheIsNull() {
            addCriterion("mabainghe is null");
            return (Criteria) this;
        }

        public Criteria andMabaingheIsNotNull() {
            addCriterion("mabainghe is not null");
            return (Criteria) this;
        }

        public Criteria andMabaingheEqualTo(String value) {
            addCriterion("mabainghe =", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheNotEqualTo(String value) {
            addCriterion("mabainghe <>", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheGreaterThan(String value) {
            addCriterion("mabainghe >", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheGreaterThanOrEqualTo(String value) {
            addCriterion("mabainghe >=", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheLessThan(String value) {
            addCriterion("mabainghe <", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheLessThanOrEqualTo(String value) {
            addCriterion("mabainghe <=", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheLike(String value) {
            addCriterion("mabainghe like", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheNotLike(String value) {
            addCriterion("mabainghe not like", value, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheIn(List<String> values) {
            addCriterion("mabainghe in", values, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheNotIn(List<String> values) {
            addCriterion("mabainghe not in", values, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheBetween(String value1, String value2) {
            addCriterion("mabainghe between", value1, value2, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andMabaingheNotBetween(String value1, String value2) {
            addCriterion("mabainghe not between", value1, value2, "mabainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheIsNull() {
            addCriterion("tenbainghe is null");
            return (Criteria) this;
        }

        public Criteria andTenbaingheIsNotNull() {
            addCriterion("tenbainghe is not null");
            return (Criteria) this;
        }

        public Criteria andTenbaingheEqualTo(String value) {
            addCriterion("tenbainghe =", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheNotEqualTo(String value) {
            addCriterion("tenbainghe <>", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheGreaterThan(String value) {
            addCriterion("tenbainghe >", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheGreaterThanOrEqualTo(String value) {
            addCriterion("tenbainghe >=", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheLessThan(String value) {
            addCriterion("tenbainghe <", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheLessThanOrEqualTo(String value) {
            addCriterion("tenbainghe <=", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheLike(String value) {
            addCriterion("tenbainghe like", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheNotLike(String value) {
            addCriterion("tenbainghe not like", value, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheIn(List<String> values) {
            addCriterion("tenbainghe in", values, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheNotIn(List<String> values) {
            addCriterion("tenbainghe not in", values, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheBetween(String value1, String value2) {
            addCriterion("tenbainghe between", value1, value2, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andTenbaingheNotBetween(String value1, String value2) {
            addCriterion("tenbainghe not between", value1, value2, "tenbainghe");
            return (Criteria) this;
        }

        public Criteria andMabhIsNull() {
            addCriterion("mabh is null");
            return (Criteria) this;
        }

        public Criteria andMabhIsNotNull() {
            addCriterion("mabh is not null");
            return (Criteria) this;
        }

        public Criteria andMabhEqualTo(String value) {
            addCriterion("mabh =", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotEqualTo(String value) {
            addCriterion("mabh <>", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhGreaterThan(String value) {
            addCriterion("mabh >", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhGreaterThanOrEqualTo(String value) {
            addCriterion("mabh >=", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhLessThan(String value) {
            addCriterion("mabh <", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhLessThanOrEqualTo(String value) {
            addCriterion("mabh <=", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhLike(String value) {
            addCriterion("mabh like", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotLike(String value) {
            addCriterion("mabh not like", value, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhIn(List<String> values) {
            addCriterion("mabh in", values, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotIn(List<String> values) {
            addCriterion("mabh not in", values, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhBetween(String value1, String value2) {
            addCriterion("mabh between", value1, value2, "mabh");
            return (Criteria) this;
        }

        public Criteria andMabhNotBetween(String value1, String value2) {
            addCriterion("mabh not between", value1, value2, "mabh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table schema01.listening
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schema01.listening
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 14 08:42:14 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}