package com.fois.Back_end_fois_smile.entity;

public class Listening {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.listening.mabainghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabainghe;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.listening.tenbainghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenbainghe;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.listening.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.listening.mabainghe
     * @return  the value of schema01.listening.mabainghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabainghe() {
        return mabainghe;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.listening.mabainghe
     * @param mabainghe  the value for schema01.listening.mabainghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabainghe(String mabainghe) {
        this.mabainghe = mabainghe;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.listening.tenbainghe
     * @return  the value of schema01.listening.tenbainghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenbainghe() {
        return tenbainghe;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.listening.tenbainghe
     * @param tenbainghe  the value for schema01.listening.tenbainghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenbainghe(String tenbainghe) {
        this.tenbainghe = tenbainghe;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.listening.mabh
     * @return  the value of schema01.listening.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabh() {
        return mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.listening.mabh
     * @param mabh  the value for schema01.listening.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabh(String mabh) {
        this.mabh = mabh;
    }
}