package com.fois.Back_end_fois_smile.entity;

public class Progress {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.matd
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Integer matd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.tuvung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Boolean tuvung;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.nguphap
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Boolean nguphap;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.nghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Boolean nghe;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.baitap
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Boolean baitap;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private Integer matk;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.progress.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabh;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.matd
     * @return  the value of schema01.progress.matd
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMatd() {
        return matd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.matd
     * @param matd  the value for schema01.progress.matd
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMatd(Integer matd) {
        this.matd = matd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.tuvung
     * @return  the value of schema01.progress.tuvung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Boolean getTuvung() {
        return tuvung;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.tuvung
     * @param tuvung  the value for schema01.progress.tuvung
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTuvung(Boolean tuvung) {
        this.tuvung = tuvung;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.nguphap
     * @return  the value of schema01.progress.nguphap
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Boolean getNguphap() {
        return nguphap;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.nguphap
     * @param nguphap  the value for schema01.progress.nguphap
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNguphap(Boolean nguphap) {
        this.nguphap = nguphap;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.nghe
     * @return  the value of schema01.progress.nghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Boolean getNghe() {
        return nghe;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.nghe
     * @param nghe  the value for schema01.progress.nghe
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNghe(Boolean nghe) {
        this.nghe = nghe;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.baitap
     * @return  the value of schema01.progress.baitap
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Boolean getBaitap() {
        return baitap;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.baitap
     * @param baitap  the value for schema01.progress.baitap
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setBaitap(Boolean baitap) {
        this.baitap = baitap;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.matk
     * @return  the value of schema01.progress.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMatk() {
        return matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.matk
     * @param matk  the value for schema01.progress.matk
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMatk(Integer matk) {
        this.matk = matk;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.progress.mabh
     * @return  the value of schema01.progress.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabh() {
        return mabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.progress.mabh
     * @param mabh  the value for schema01.progress.mabh
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabh(String mabh) {
        this.mabh = mabh;
    }
}