package com.fois.Back_end_fois_smile.entity;

public class QuestionSection {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.question_section.maphan
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maphan;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.question_section.tenphan
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenphan;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.question_section.maphan
     * @return  the value of schema01.question_section.maphan
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaphan() {
        return maphan;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.question_section.maphan
     * @param maphan  the value for schema01.question_section.maphan
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaphan(String maphan) {
        this.maphan = maphan;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.question_section.tenphan
     * @return  the value of schema01.question_section.tenphan
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenphan() {
        return tenphan;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.question_section.tenphan
     * @param tenphan  the value for schema01.question_section.tenphan
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenphan(String tenphan) {
        this.tenphan = tenphan;
    }
}