package com.fois.Back_end_fois_smile.entity;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schema01.reply.marep
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    private Integer marep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schema01.reply.ndrep
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    private String ndrep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schema01.reply.thoigian
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    private Date thoigian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schema01.reply.mabl
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    private Integer mabl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schema01.reply.matk
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    private Integer matk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schema01.reply.marep
     *
     * @return the value of schema01.reply.marep
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMarep() {
        return marep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schema01.reply.marep
     *
     * @param marep the value for schema01.reply.marep
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public void setMarep(Integer marep) {
        this.marep = marep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schema01.reply.ndrep
     *
     * @return the value of schema01.reply.ndrep
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public String getNdrep() {
        return ndrep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schema01.reply.ndrep
     *
     * @param ndrep the value for schema01.reply.ndrep
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public void setNdrep(String ndrep) {
        this.ndrep = ndrep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schema01.reply.thoigian
     *
     * @return the value of schema01.reply.thoigian
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public Date getThoigian() {
        return thoigian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schema01.reply.thoigian
     *
     * @param thoigian the value for schema01.reply.thoigian
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public void setThoigian(Date thoigian) {
        this.thoigian = thoigian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schema01.reply.mabl
     *
     * @return the value of schema01.reply.mabl
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMabl() {
        return mabl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schema01.reply.mabl
     *
     * @param mabl the value for schema01.reply.mabl
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public void setMabl(Integer mabl) {
        this.mabl = mabl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schema01.reply.matk
     *
     * @return the value of schema01.reply.matk
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public Integer getMatk() {
        return matk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schema01.reply.matk
     *
     * @param matk the value for schema01.reply.matk
     *
     * @mbg.generated Thu May 06 20:20:23 ICT 2021
     */
    public void setMatk(Integer matk) {
        this.matk = matk;
    }
}