package com.fois.Back_end_fois_smile.entity;

public class Structure {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.structure.mact
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mact;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.structure.tenct
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.structure.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String nghia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.structure.chuy
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String chuy;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.structure.manp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String manp;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.structure.mact
     * @return  the value of schema01.structure.mact
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMact() {
        return mact;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.structure.mact
     * @param mact  the value for schema01.structure.mact
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMact(String mact) {
        this.mact = mact;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.structure.tenct
     * @return  the value of schema01.structure.tenct
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenct() {
        return tenct;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.structure.tenct
     * @param tenct  the value for schema01.structure.tenct
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenct(String tenct) {
        this.tenct = tenct;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.structure.nghia
     * @return  the value of schema01.structure.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getNghia() {
        return nghia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.structure.nghia
     * @param nghia  the value for schema01.structure.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNghia(String nghia) {
        this.nghia = nghia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.structure.chuy
     * @return  the value of schema01.structure.chuy
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getChuy() {
        return chuy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.structure.chuy
     * @param chuy  the value for schema01.structure.chuy
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setChuy(String chuy) {
        this.chuy = chuy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.structure.manp
     * @return  the value of schema01.structure.manp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getManp() {
        return manp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.structure.manp
     * @param manp  the value for schema01.structure.manp
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setManp(String manp) {
        this.manp = manp;
    }
}