package com.fois.Back_end_fois_smile.entity;

public class Word {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.word.machu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String machu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.word.tenchu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String tenchu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.word.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String nghia;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.word.amtiet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String amtiet;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.word.mabang
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String mabang;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schema01.word.maloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    private String maloaitu;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.word.machu
     * @return  the value of schema01.word.machu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMachu() {
        return machu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.word.machu
     * @param machu  the value for schema01.word.machu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMachu(String machu) {
        this.machu = machu;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.word.tenchu
     * @return  the value of schema01.word.tenchu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getTenchu() {
        return tenchu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.word.tenchu
     * @param tenchu  the value for schema01.word.tenchu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setTenchu(String tenchu) {
        this.tenchu = tenchu;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.word.nghia
     * @return  the value of schema01.word.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getNghia() {
        return nghia;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.word.nghia
     * @param nghia  the value for schema01.word.nghia
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setNghia(String nghia) {
        this.nghia = nghia;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.word.amtiet
     * @return  the value of schema01.word.amtiet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getAmtiet() {
        return amtiet;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.word.amtiet
     * @param amtiet  the value for schema01.word.amtiet
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setAmtiet(String amtiet) {
        this.amtiet = amtiet;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.word.mabang
     * @return  the value of schema01.word.mabang
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMabang() {
        return mabang;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.word.mabang
     * @param mabang  the value for schema01.word.mabang
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMabang(String mabang) {
        this.mabang = mabang;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schema01.word.maloaitu
     * @return  the value of schema01.word.maloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public String getMaloaitu() {
        return maloaitu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schema01.word.maloaitu
     * @param maloaitu  the value for schema01.word.maloaitu
     * @mbg.generated  Thu May 06 20:20:23 ICT 2021
     */
    public void setMaloaitu(String maloaitu) {
        this.maloaitu = maloaitu;
    }
}